name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Verificar estrutura de diretórios
      run: ls -la

    - name: Instalar dependências
      run: npm install

    - name: Instalar Playwright
      run: npm install --unsafe-perm=true

    - name: Executar testes
      run: npx playwright test

    - name: Gerar relatório
      run: npx playwright test --reporter=html