name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do código
      uses: actions/checkout@v3

    - name: Instalar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Verificar estrutura de diretórios
      run: ls -la
      
    - name: Instalar dependências
      run: npm ci

    - name: Instalar navegadores do Playwright
      run: npx playwright install --with-deps

    - name: Executar testes
      run: npx playwright test --reporter=html

    - name: Upload do relatório de testes
      uses: actions/upload-artifact@v3
      if: always()
      with:
          name: playwright-report
          path: playwright-report