name: Playwright Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar dependências com permissões elevadas
        run: npm install --unsafe-perm=true

      - name: Instalar navegadores do Playwright
        run: npx playwright install

      - name: Executar testes
        run: npx playwright test